# Generated by Django 5.1.7 on 2025-03-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='contact',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
